### ISSUE TITLE
1.20.2 launch issue

### ISSUE THREAD

**Issue by MrRoomba69** [mrshmllow/BetterRecipeBook#90] opened 2023-11-12 22:05 UTC
when i launch my mod pack, it crashes. a part of the crash report says this mod caused it.
"java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'brb'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$ehk000$notenoughcrashes$catchFabricInit(class_310.java:29595)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalAccessError: failed to access class net.minecraft.class_5411$class_5412 from class marsh.town.brb.api.BRBBookSettings (net.minecraft.class_5411$class_5412 and marsh.town.brb.api.BRBBookSettings are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @31a5c39e)
	at marsh.town.brb.api.BRBBookSettings.registerBook(BRBBookSettings.java:21)
	at marsh.town.brb.util.BRBHelper.createBook(BRBHelper.java:21)
	at marsh.town.brb.BetterRecipeBook.<clinit>(BetterRecipeBook.java:29)
	at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)"

**Comment by MrRoomba69** [comment] 2023-11-12 22:11
[crash-2023-11-12_17.02.41-client.txt](https://github.com/mrshmllow/BetterRecipeBook/files/13329307/crash-2023-11-12_17.02.41-client.txt)
here is the full crash report

**Comment by Atticuss26** [comment] 2023-11-12 23:01
Having the same issue.
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'brb'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalAccessError: failed to access class net.minecraft.class_5411$class_5412 from class marsh.town.brb.api.BRBBookSettings (net.minecraft.class_5411$class_5412 and marsh.town.brb.api.BRBBookSettings are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @452e26d0)
	at marsh.town.brb.api.BRBBookSettings.registerBook(BRBBookSettings.java:21)
	at marsh.town.brb.util.BRBHelper.createBook(BRBHelper.java:21)
	at marsh.town.brb.BetterRecipeBook.<clinit>(BetterRecipeBook.java:29)
	at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 9 more

**Comment by mrshmllow** [comment] 2023-11-13 05:10
duplicate of #89

**Closed by mrshmllow** 2023-11-13 05:10 UTC
Labels: duplicate
